services:
  postgres:
    image: postgres:15
    container_name: tashtebat-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-tashtebat-backend
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: tashtebat-redis
    restart: always
    ports:
      - "6379:6379"

  medusa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tashtebat-medusa
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@tashtebat-postgres:5432/medusa-tashtebat-backend?sslmode=disable
      REDIS_URL: redis://redis:6379
      ADMIN_CORS: http://localhost:9000
      STORE_CORS: http://localhost:8000

volumes:
  postgres_data:
