version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: tashtebat-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-tashtebat-backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: tashtebat-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
